sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 11
install:
  - yarn install
  - npm install -g codecov
script:
  - yarn test
  - yarn test:coverage
  - yarn lint:ts
after_script: "cat ./coverage/lcov.info | $(npm bin)/codecov"
branches:
  only:
  - master
  - /^greenkeeper/.*$/
notifications:
  email:
    recipients:
    - phucnguyenhoang1985@gmail.com
    on_success: change
    on_failure: always