sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
install:
  - yarn install
  - npm install -g codecov
scripts:
  - yarn test
  - yarn test:coverage
  - yarn lint
after_success: "cat ./coverage/lcov.info | $(npm bin)/codecov"
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - phucnguyenhoang1985@gmail.com
    on_success: change
    on_failure: always